### ISSUE TITLE
APCs not registering depletion and recharging

### ISSUE THREAD

**Issue by SerynEngi** [BeeStation/NSV13#1154]
Noted on the most recent test round and on an eclipse round prior to (apologies for not having round ID or a screenshot for that one). APCs were registering fully charged without being fully charged, leading to APC depletion. 

https://cdn.discordapp.com/attachments/779423309011091486/792858101472165909/APC_not_charging.PNG

This is an example of one such APC. This particular one was depleted by Ethereal eating, and the power going to it was verified intact. Note how it registers the APC as fully charged.

**Comment by Bokkiewokkie** [comment]
After a convo in #developement on the discord we concluded that this issue happens due to the APC not registering its battery being drained while it's connected to the grid. A solution for this would be to add things that drain power (IPC's or Ethereals) to the enviromental power channel temporarily while they're draining the APC instead of taking power directly out of the battery.

**Comment by SerynEngi** [comment]
This appears to have been fixed with the most recent beebase, and has not been seen since.
