### ISSUE TITLE
Beebase issues

### ISSUE THREAD

**Issue by covertcorvid** [BeeStation/NSV13#1336]
FTL parallax doesn't work
View variables sometimes doesn't load

**Comment by covertcorvid** [comment]
No supply shuttle on Gladius

**Comment by Bobbanz1** [comment]
![image](https://user-images.githubusercontent.com/59128051/114265004-9f5efa00-99ee-11eb-970b-aba834de9f7e.png)

**Comment by covertcorvid** [comment]
All three station projects are given at start of extended rounds

**Comment by covertcorvid** [comment]
AI multicamera window is static

**Comment by covertcorvid** [comment]
RBMK doesn't produce power???

**Comment by covertcorvid** [comment]
Tycoon has no caps_spare safe

**Comment by covertcorvid** [comment]
Personally purchased crate wouldn't unlock

**Comment by AU518987077** [comment]
As AI i keep losing the ability to interface with machines with new windows after a short while, and having to resolve this by reconnecting with the file option.

During KMC's Atlas event 2203 i feel like i impeded the story event by not being able to answer the admirals requsts of granting access to the critical systems part of the atlas, i could not interface with the turret controls, the APC controls, the door controls outside of alt and contorl clicks without having to hit File>Reconnect which leads to my actual annoyance.

all the consoles and computers i interface with, i leave open and keep on my second monitor, reconnecting loses those windows, they stay open but become unconnected to the machines they are controlling and require closing those windows and re-acquiring them. which besides being annoying, hurts my ability to perform requests no matter what part of the ship i am actively looking at in normal camera or multi camera mode.

this screenshot is what i mean by having all these things in "memory bank 2" the main byond window is fullscreen on my main monitor , the left two thirds in this screenshot, and everything that is on the right one third is the second monitor, having to hunt down each of those consoles is different on each ship, and having to reconnect once or twice is tolerable due to actual connection issue.
but at the moment, its too much, especially on the aetherwhisp when all engines are running, SD, AGCNR, SM, TEG, you can see why, i need a bigger side panel to add more windows. but what i have is barely enough
![Screenshot 2021-02-19 22 03 51](https://user-images.githubusercontent.com/24924661/114301362-a8e57200-9a81-11eb-8924-0c0f378397ed.png)

i will attempt to determine a time frame as to when this is happening, but in the meantime my byond client version is 513.1539 this was never the case prior except when i mistaken "hide" windows under other windows, hence the cascade stack in this (and all screenshots i ever shared on discord)screenshot example.

**Comment by covertcorvid** [comment]
> 
> 
> As AI i keep losing the ability to interface with machines with new windows after a short while, and having to resolve this by reconnecting with the file option.
> 
> During KMC's Atlas event 2203 i feel like i impeded the story event by not being able to answer the admirals requsts of granting access to the critical systems part of the atlas, i could not interface with the turret controls, the APC controls, the door controls outside of alt and contorl clicks without having to hit File>Reconnect which leads to my actual annoyance.
> 
> all the consoles and computers i interface with, i leave open and keep on my second monitor, reconnecting loses those windows, they stay open but become unconnected to the machines they are controlling and require closing those windows and re-acquiring them. which besides being annoying, hurts my ability to perform requests no matter what part of the ship i am actively looking at in normal camera or multi camera mode.
> 
> this screenshot is what i mean by having all these things in "memory bank 2" the main byond window is fullscreen on my main monitor , the left two thirds in this screenshot, and everything that is on the right one third is the second monitor, having to hunt down each of those consoles is different on each ship, and having to reconnect once or twice is tolerable due to actual connection issue.
> but at the moment, its too much, especially on the aetherwhisp when all engines are running, SD, AGCNR, SM, TEG, you can see why, i need a bigger side panel to add more windows. but what i have is barely enough
> ![Screenshot 2021-02-19 22 03 51](https://user-images.githubusercontent.com/24924661/114301362-a8e57200-9a81-11eb-8924-0c0f378397ed.png)
> 
> i will attempt to determine a time frame as to when this is happening, but in the meantime my byond client version is 513.1539 this was never the case prior except when i mistaken "hide" windows under other windows, hence the cascade stack in this (and all screenshots i ever shared on discord)screenshot example.

Looks like there's a cap on the number of TGUI windows the game will let you have open. Is it that you can't open any more windows after you have 9, or are you seeing other issues as well?

**Comment by AU518987077** [comment]
> As AI i keep losing the ability to interface with machines with new windows after a short while, and having to resolve this by reconnecting with the file option.
> 
> During KMC's Atlas event 2203 i feel like i impeded the story event by not being able to answer the admirals requsts of granting access to the critical systems part of the atlas, i could not interface with the turret controls, the APC controls, the door controls outside of alt and contorl clicks without having to hit File>Reconnect which leads to my actual annoyance.
> 
> all the consoles and computers i interface with, i leave open and keep on my second monitor, reconnecting loses those windows, they stay open but become unconnected to the machines they are controlling and require closing those windows and re-acquiring them. which besides being annoying, hurts my ability to perform requests no matter what part of the ship i am actively looking at in normal camera or multi camera mode.
> 
> this screenshot is what i mean by having all these things in "memory bank 2" the main byond window is fullscreen on my main monitor , the left two thirds in this screenshot, and everything that is on the right one third is the second monitor, having to hunt down each of those consoles is different on each ship, and having to reconnect once or twice is tolerable due to actual connection issue.
> but at the moment, its too much, especially on the aetherwhisp when all engines are running, SD, AGCNR, SM, TEG, you can see why, i need a bigger side panel to add more windows. but what i have is barely enough
> ![Screenshot 2021-02-19 22 03 51](https://user-images.githubusercontent.com/24924661/114301362-a8e57200-9a81-11eb-8924-0c0f378397ed.png)
> 
> i will attempt to determine a time frame as to when this is happening, but in the meantime my byond client version is 513.1539 this was never the case prior except when i mistaken "hide" windows under other windows, hence the cascade stack in this (and all screenshots i ever shared on discord)screenshot example.

naw it was never when i was adding windows, it is always after i havea dded all the windwos i normally have, and then i open a bucnha nd clsoe a bunch, like flip though a bunch of SMES's a bunch fo APC's turret controls, then just look around talk for a bit, then i go to open a door control or APC again and i cant open anything and have to hit file>reconnect i will be uploading this weekend's videos this week i can link you to timestamps of these events then. do you want me to do that? or make soem quick clips here? tiem compressed of course.

**Comment by covertcorvid** [comment]
sure, a clip or video would be helpful. I'll keep trying to repro it as well.

**Comment by covertcorvid** [comment]
XO name chat color is default

**Comment by Bokkiewokkie** [comment]
Chain of command order for cap's spare ID safe is wack.
![image](https://user-images.githubusercontent.com/43698041/114374997-85572000-9b84-11eb-963e-01a1ec45cb0e.png)

**Comment by covertcorvid** [comment]
> got another one, as a borg shell or ai lookign at the magnet controls, i cant pull or push an asteroid

**Comment by covertcorvid** [comment]
> Bobbanz1 | Supply Gang Ruby — Today at 7:01 AM
> Yo why the hell does the chemical Perfluorodecalin have a description that says it deals significant damage to the lungs if overdosed
> However the code itself says that if overdosed it will deal damage to the heart

**Comment by AU518987077** [comment]
> sure, a clip or video would be helpful. I'll keep trying to repro it as well.



https://user-images.githubusercontent.com/24924661/114688959-767e8380-9cd2-11eb-9154-4f9268a1aa05.mp4

**Comment by AU518987077** [comment]
[![](http://img.youtube.com/vi/p37XhI76L84/0.jpg)](https://youtu.be/p37XhI76L84?list=PLMDmYuVZH5LN25LJBZel8RPZoGniI8m7y&t=4068 "got stuck on .50cal unable to move as a Ai controlled medical shell. disconnecting from the shell did not fix this, had to reconnect via file>reconnect")
got stuck on .50cal unable to move as a Ai controlled medical shell. disconnecting from the shell did not fix this, had to reconnect via file>reconnect.
chat was still scrolling, in fact there is a condition zebra announcement that passes chat and i heard not of it in this state, you can see in my second monitor that Dradis window went form a orange eye to a green eye so i was in the .50 cal

might be related to the above issue, might be something different, only happened once.
