### ISSUE TITLE
Squad loadoat too big for backpacks.

### ISSUE THREAD

**Issue by James-source** [BeeStation/NSV13#1440]
## Round ID:
All rounds with boarding

## Testmerges:
Boarding?

## Reproduction:
-Be squad medic (or other, I only got to test medic)
-get hazard squad gear
-do things with it
-your medkit is empty, your mags are empty
-try to refund it so you can get a refill
-fail at fitting every item into your backpack, be unable to return equipment because of it.
Either slim down the given equipment loadouts(maybe don't give out the uniform, seems pointless anyway), or make it be able to take items seperately.

Or maybe you could make the vendor a sort of item list, where you can store and return your loadout items seperately, maybe even pay for ammo refills, or medkit refills or something.

Another solution might be to make a box that works like belts, where it allows only the squad related equipment inside. and you just put it all into the box and it refunds the box, and if there are items missing, you get a pay cut or something. Maybe a "bluespace loadout box" that only stores things related to your squad role

**Comment by Bokkiewokkie** [comment]
Right now this issue is solved by the equipment vendor also returning items if they are inside your backpack (when you insert the box), so if you, for example, put the marine armor in your backpack while handing in the box with the rest of the items it will take the armor out of your backpack.

I do think this should be done more elegantly though, and right now there is nothing in-game that lets you know that this is how it works (maybe make the message saying you can't return it say something about that?)

**Comment by James-source** [comment]
you can return things while they are still in the box? huh.
Maybe adjusting the message it gives you when it declines the return to include what exactly is missing is a good idea then.
