### ISSUE TITLE
Ethereals fast power hunger.

### ISSUE THREAD

**Issue by Ambulo-gif** [BeeStation/NSV13#1512]
Race of ethereals has an issue with the time between recharging itself. For a human race it's like 40 minutes before they go from "I'm stuffed" to "I'm getting quite hungry" (didn't count) but for ethereals it's around 15 minutes (I counted) before it starts being "low on power". 
When we look at other races, the only one with that issue are ethereals. Other races have "normal" time they have between "meals" in comparison to ethereals.
I'd love for the Ethereal race to be "buffed" in this matter so it can be as enjoyable to play (without having to worry about running out of power and dying) as other races are.

**Comment by Bokkiewokkie** [comment]
So this is actually something someone ported from TG (#967) and was discussed further in the discord (Link to conversation:https://discord.com/channels/602204464417472601/602204705862582341/779698216958034001) and I highly suggest reading it and talking to Seryn about this seeing as he's a regular ethereal player. Because I'm not that familiar with play as an ethereal myself I'll be happy to implement any things you'd like to see changed/added if you put them in this thread later assuming it's nothing absurd.
