### ISSUE TITLE
You cannot repair Gauss Turrets and use them afterward

### ISSUE THREAD

**Issue by bluewasabi24** [BeeStation/NSV13#1855]
## Reproduction:
Destroy gauss by any means necessary. Disassembling is also fine, I guess.
Rebuild the gauss turret on the upper deck.
Rebuild the gauss chair wherever you want on the lower deck. Preferably underneath the turret, but you'll see why it doesn't matter in a bit.
Buckle yourself to the chair. If you're lucky, you'll go up into the turret.
Once in the turret, click frantically at the control panel and realize you can't do anything.
Descend from the gauss turret. 
Repeat at necessary to further cement that you cannot rebuild the gauss turret and be able to use it afterward.

I've done some testing on this with someone else on the test server. We've tried wacking them with multitools, we've tried moving the construction of the gauss turret and chair, we've tried building the chair first THEN the turret, all to no avail. 

Also, the sprite for the gauss turret doesn't line up with anything once rebuilt. Below is a picture of a rebuild turret. The red is where the machine frame was assembled, the yellow is where the hitbox actually is, and you can see the sprite for yourself 

![image](https://user-images.githubusercontent.com/40776129/158281832-2698aabf-93ba-4e58-8564-119d4cc75da7.png)

**Comment by TheFakeElon** [comment]
I'm surprised you were able to raise the chair with the weird turf placement, it should have failed as far as I can see, could be the source of the bug?
![image](https://user-images.githubusercontent.com/59686430/160498238-e9b5a085-fd96-40f0-9825-45ef76fa685b.png)

I'm not sure what's with the offset though, unless mappers did some hacky offset, it should initialize with the same offset as every other gun

**Comment by Kenionatus** [comment]
The offset might be the issue here. The gauss properly spawns a rack one y south and one z below its loc. In my testing, the loc is where the frame was assembled, which is in the centre of the hitbox (so where the gauss shells are in OPs picture, one square below the yellow box). Building a chair anywhere underneath the hitbox or building the gauss so the hitbox is over a chair seems to properly link the two. Ascending and descending work and the two show up in their respective variables. Descending is always below the gauss's loc, even if the chair was built offset. Both adminghosting and using the gun camera verb show the gunners location at the guns loc.

My biggest lead currently is that the UI of the rebuilt gauss shows the orange "you're too far away to interact but close enough to see" eye if it is entered by the player.

It doesn't seem to make a difference whether the player enters the gun through the chair or directly, although getting out of a gun without chair puts one in the centre of its hitbox, unable to move.
