### ISSUE TITLE
Various Mapping issues on NSV Snake

### ISSUE THREAD

**Issue by williamcll** [BeeStation/NSV13#1862]
## Round ID: 
3985

## Testmerges:
[#1861: 'Snake Class medium gunboat' by Vasily2013 at commit 6ec99fa041](https://github.com/BeeStation/NSV13/pull/1861)

## Reproduction:
Right now there's multiple issues for the new NSV snake including:
The ORM is not connected to any of the lathes
Deck 1 has no radio signals
Medbots have no patrol route
Exosuit fabricator prints items downwards instead of the right

**Comment by bluewasabi24** [comment]
ORM isn't connected because you need to manually make the ore silo.

**Comment by DeltaFire15** [comment]
agcnr nucleium filter should be on cold side of loop unless intended to be improvement potential
tcomms door is just called engineering wing despite only leading to the tcomms room
tcomms top deck has no relay still
armor pumps don't have sufficient starter material types (plas, silver, iron, titanium)
agcnr cooling loop insufficient to keep the reactor cooled at any fuel input
no layer adapters on agcnr cooling pipes (when fixed still insufficient without changes to the former)

**Comment by Absolutely-Steph** [comment]
The genetics door is labelled exam room
I wish it utilised genpop but we can't all have nice things
does surgery start with a comfy chair? the heck?
multi deck pipe adapter on top of munidrobe in munitions

**Comment by Absolutely-Steph** [comment]
also:
![image](https://user-images.githubusercontent.com/56017258/159133454-205f9243-a379-40a2-be11-afe519f4c7cf.png)
weird radiation hole under kitchen

**Comment by red031000** [comment]
cargo does not have a freight delivery console linked to the torpedo tube, in fact there isn't one there at all

**Comment by someone543** [comment]
There is no designated landing zone for delivery and pickup crates, causing them to land anywhere

**Comment by Bokkiewokkie** [comment]
@Vasily2013

**Comment by Vasily2013** [comment]
- Silo was added, so issues related to that are fixed.
- Unable to replicate deck 1 radio issues on current patch.
- Bot patrol routs are cancer and I'll learn how to do them in a follow on PR.
- Exosuit fab will have an edited var which might fix it in the next patch.
- ANGCR no longer used. 
- Tcomms door has been fixed. 
- Armor pumps have equivalent material to other ships.
- genetics door renamed
- Munidrobe moved.
- Area without area outside of kitchen has an area now.
- Supply launching should already be fixed in a previous patch
- Trader sending targets added in next patch.


Follow on PRs
- Bot pathing
- Genpop?

**Comment by williamcll** [comment]
most of these should be fixed, last time I checked.
