### ISSUE TITLE
Modcomp app Marlowe Treeby's Art Galaxy doesn't work

### ISSUE THREAD

**Issue by someone543** [BeeStation/NSV13#2117]
## Reproduction:
The modular computer app Marlowe Treeby's Art Galaxy will not work when opened. Instead, it will give this error message.
![BrokenArt](https://user-images.githubusercontent.com/95106800/197379918-59d08113-cc9f-4a7c-8a8f-0934be57aeb7.PNG)

1. Get a modular computer and download Marlowe Treeby's Art Galaxy
2. Attempt to open the app
3. See above

**Comment by Bobbanz1** [comment]
This issue is being caused because there are no maps that have persistent painting frames placed down and since those don’t exist on any maps, it means nobody has saved a painting to the database, which ultimately means there’s actually nothing for this TGUI interface to load and as such it’s just throwing an error

**Comment by Bokkiewokkie** [comment]
This should be fixed now

**Comment by someone543** [comment]
![artworks](https://user-images.githubusercontent.com/95106800/200105114-57bc1851-56d0-4288-89ff-38861215d18c.PNG)

Fixed, closing
