### ISSUE TITLE
Runtime in squad_lead_finder.dm, line 48: Cannot read null.z

### ISSUE THREAD

**Issue by covertcorvid** [BeeStation/NSV13#2147]

**Comment by Bobbanz1** [comment]
Needs further details on how one would go about replicating this. 

Currently what's happening in the code at that moment is that it's checking if the Squad Leader's Z-level is not the same as the User's Z-level. 

Only reason I can see how this would happen is if for some reason a mob got assigned as either a Squad Lead while not existing in any Z-level...which should be impossible since even the lobby has a Z-level...or it tried to grab the Z-level of the Squad Member who wasn't on any Z-level at all...Actually hang on found something in the Pinpointer code that might fix this issue, however without any ability to reproduce the issue I have no way of knowing if it's actually fixed or not.
