### ISSUE TITLE
Telecom code is a hot fucking mess [THANKS DOOHL]

### ISSUE THREAD

**Issue by DrSirKnight** [BeeStation/NSV13#253]
AI sat intercom has access to red and blue CTF radio channels, can both hear and talk over them. It can also talk over syndicate channels but can't hear anything. It also has access to centcom channel which seems like it might of not been intended.

## Reproduction:

Be AI, click on intercom, turn the mic on, set channel to 121.3 (Syndicate, need a human with syndicate headset to hear it since AI doesn't have decryption key to actually hear it), 121.7 (Blue CTF), 121.5 (Red CTF), 133.7 (Centcom), and proceed to talk

**Comment by francinum** [comment]
The AI's headset is classed as `independent`, there should probably be a different check for ATC radio-compliance instead of the generic check for superspace transport support

**Comment by Bokkiewokkie** [comment]
This is because the intercoms have freerange set to 1 instead of 0 (which is normally used in Ratvar intercoms because they need to be able to switch to all channels), allowing you to enter a frequency below 144.5 into the intercoms and thus being able to talk through the channels. The reason they can't hear the syndie channels is because they still have the syndie = FALSE set like the default radio's.

**Comment by Bokkiewokkie** [comment]
I think the solution would just be adding a tag like 'syndie' for the ctf and centcom channels aswell and changing the tag to disallow setting your radio to the specific channels to avoid being able to even interact with them or canceling both the receiving _and_ the sending of messages across the channels.

**Comment by Bokkiewokkie** [comment]
actually independent is already the centcom var for being able to use the channel and the radios have it set to TRUE so that's probably intended

**Comment by Bokkiewokkie** [comment]
wait someone slammed the CTF and ATC radios onto the 'independent' var aswell. So the problem is just that someone probably gave the AI radio that so it could hear ATC radio instead of just making a seperate var for it because they couldn't be bothered to copy the bit of code that makes the radio ignore Z levels

**Comment by francinum** [comment]
This is untenable to fix.
