### ISSUE TITLE
AI tracking window is broken

### ISSUE THREAD

**Issue by benbot16** [BeeStation/NSV13#2566]
## Round ID:
6863

## Testmerges:

![image](https://github.com/BeeStation/NSV13/assets/9423435/50a45346-8317-4450-8421-5b34fd80000f)

## Reproduction:

1. Open the "track with camera" window
2. Window is blank

**Comment by Bobbanz1** [comment]
Probably caused by this PR as it's the PR that introduced the window.
#2415

**Comment by Bobbanz1** [comment]
Hmmm...interesting, found another issue while trying to figure out a fix to this, however that issue was as a result of what I altered. 

If this issue continues to happen could you grab a screenshot of the TGUI window and upload it to this issue? 
And could you also see if pressing this button fixes the issue assuming you get the search bar and the TGUI window to appear, but the rest of the window contains no actual information?

![Skärmbild 2023-11-09 085954](https://github.com/BeeStation/NSV13/assets/59128051/7cc0146f-8c9d-4e39-86ba-9721f9bd5576)

**Comment by DeltaFire15** [comment]
Still occurs, refresh does not affect it. Sometimes fixes itself after some time, usually occurs midround for reasons I am not entirely sure about. Potentially null entry / bad GC?
