### ISSUE TITLE
Atlas and Eclipse Gauss turrets are outside of powered areas

### ISSUE THREAD

**Issue by DeanYktRu** [BeeStation/NSV13#2602]
## Round ID:
7149

## Reproduction:
Gauss guns tend to get destroyed by explosions during combat. While everything may be repaired, there's issue, however. After reassembling the gauss turret, as you climb in, the gauss status window is greyed out and inoperable as if you are too far away. As a result, you'll no longer be able to man the gauss gun and that turret is considered to be permanently destroyed.

**Comment by Bobbanz1** [comment]
I have been unable to replicate this issue through the steps provided here, even with the chair itself being destroyed and one having to manually climb into the gauss turret itself. 

Local branch is up to the latest, only way I encountered this issue was if the maintenance panel on the gauss turret itself was unscrewed, at which point it would leave the TGUI window in the same state as if the person is too far away from the gun itself.

**Comment by DeanYktRu** [comment]
It happened on both Eclipse and Atlas. The chair was intact as explosion didn't destroy it. And I thought the reassembled guns have their maintenance panel automatically screwed?

**Comment by Bobbanz1** [comment]
> It happened on both Eclipse and Atlas. The chair was intact as explosion didn't destroy it. And I thought the reassembled guns have their maintenance panel automatically screwed?

That is due to the map itself not having those be part of the gauss bay area itself, they're placed in an area that is missing an APC, therefore when constructed, for some reason the machine itself doesn't realize that and flick the value someone implemented a while ago that makes gauss turrets not require power to function. 

@Bokkiewokkie Think you can rename this issue to Gauss Turrets on Atlas/Eclipse are not part of the gauss bay area?

**Comment by Bokkiewokkie** [comment]
@Bobbanz1 
Yep
