### ISSUE TITLE
[Hammerhead] Science stuffs

### ISSUE THREAD

**Issue by Sikroth** [BeeStation/NSV13#286]
Issue reported from  Round ID: 74 (NSV 13 | Official | "MRP" | 98% Free Lag | Fresh Tupelo)

Reporting client version: 513.1505

The new xenobiology kill pen to the right has no camera. Ingame fixable by adding xray to the xenobio cameras, but there should be one there roundstart.

Also, the RnD console can't connect to the Destructive analyzer or the Protolathe, as they're too far away. Might need to shuffle them around for the rare case the destructive analyzer is used.

**Comment by Vasily2013** [comment]
Kill pen to the right was humoring someone already with the idea of not wanting to space walk to fix a camera. So now, I've given you
>A kill pen
>An airlock
>A space suit
>an extra external camera
>and an extra kill pen in maint.

Another reason why i'm not intent on resolving this issue by adding a camera is because generally maint should have no camera sight in it, and thus be safe for general antagery to take place. This allows the xenobiologist, if they are antag, to easily access an area nearby that has no camera fixture in it.

**Comment by Vasily2013** [comment]
as for the rnd console, that will be moved as of my next PR.
