### ISSUE TITLE
[Hammerhead] OLD unsupported Ident Console - customs

### ISSUE THREAD

**Issue by Karmic-Skink** [BeeStation/NSV13#543]
Hammerhead Customs has an old unsupported Identity Console sitting in it.

![image](https://user-images.githubusercontent.com/45891563/80295686-f1921580-87b3-11ea-916a-01b20482c03a.png)

**Comment by francinum** [comment]
These are not unsupported. Their code needs to be updated or reworked. Related to #419

**Comment by Karmic-Skink** [comment]
They are unsupported because I'm not supporting them.

**Comment by francinum** [comment]
There are several reasons they are being retained, outside of currently being printable through RnD And existing in Secure Tech Storage.

The only way to create new ID consoles without these boards is through construction of a modular computer, which is a somewhat complicated undertaking in comparision to standard computer construction.

Secondly, the modular computers require the NTnet to be active in order to download the ID card modification program, which may not be feasible in several cases involving smart antagonists.

I suggest that if you want to continue with the route of removing support for these consoles you get direct approval from KMC.

**Comment by Karmic-Skink** [comment]
I already have approval.

I will not be supporting these until they are replaced by the upstream TGUI 3, which may or may not even use these consoles.

If you want to pull your finger out and support them yourself, go ahead.

**Comment by Vasily2013** [comment]
> If you want to pull your finger out and support them yourself, go ahead.

This is unprofessional and the exact sort of thing that we need to start working on as a team to reduce.

**Comment by francinum** [comment]
Redundant by #419
