### ISSUE TITLE
Airlock mess megathread

### ISSUE THREAD

**Issue by francinum** [BeeStation/NSV13#558]
```
/obj/machinery/door/airlock/ship/station/glass - Missing glass overlay (Can click floor)


/obj/machinery/door/airlock/ship/station/mining - Missing glass subtype. Likely redundant.

/obj/machinery/door/airlock/ship/station/research - Missing glass subtype. Likely redundant.

/obj/machinery/door/airlock/ship/hatch - Sideways smooth has holes (can click floor)

/obj/machinery/door/airlock/ship/external - Appears to have glass but can't be seen through when closed.


/obj/machinery/door/airlock/ship/maintenance/defaultaccess - THIS IS BAD PRACTICE. GET RID OF THIS.

/obj/machinery/door/airlock/ship/medical - Missing glass subtype


/obj/machinery/door/airlock/ship/security/glass - Missing glass overlay (Appears opaque)

/obj/machinery/door/airlock/ship - Missing glass subtype

/obj/machinery/door/airlock/ship/cargo - Redundant typepath. Changes only the name.

```

**Comment by Corsaka** [comment]
I have sprites for whoever's coding this.

**Comment by Corsaka** [comment]
Most of these don't seem to be things we're using. What's the point in altering them?

**Comment by Corsaka** [comment]
Also, just generally, our timing for these airlocks is completely off - the sprite triggers twice because it's faster than the ingame open time.

**Comment by Corsaka** [comment]
Icon structure of airlocks in general seems to be a hot mess. We're using icons from four different folders rather than concatenating them into one. The only problem with doing that is upstream issues.

**Comment by Corsaka** [comment]
I'm adding notes here for anyone willing to help respriting:

* nsv13/icons/obj/machinery/doors (some are decent, some are complete ass. we should move everything we use into this folder, though)
* nsv13/goonstation/icons - has overlays preset (WHY???)
* icons/obj/doors/airlocks/station (these are the old ones that we need to eradicate from code)
* icons/obj/doors/airlocks (has a few extra ones that are still present and don't immediately need a resprite)

**Comment by francinum** [comment]
Oldlocks MUST be kept around for compatibility reasons.

**Comment by Corsaka** [comment]
Oh, yeah, absolutely, by "eradicate from code" I meant "replace every instance in code with the new icons".

**Comment by GoatMonarch** [comment]
I probably ought to mention #1390 here. Were not aware of this thread from earlier.

**Comment by covertcorvid** [comment]
Fill basically lets you use the same sprite for a glass and non-glass door. The fills cover the parts that would have glass overlays if the door isn't glass.

#1393 fixes:
- Glass subtypes and sprites
- Holes/missing overlays
- Animation jitter - setting airlock animation to only play once instead of indefinitely resolved this in the test instance
- Removed drawn-on lights from doors that don't open into the floor (couldn't work out what the shading was supposed to be)

Won't fix:
Different airlock folders. The goonstation airlocks must stay in the goonstation folder for license reasons. The sprites we don't share with Bee that are under our own license will stay in the nsv13 folder.

Remaining issues:
- Redundant door types (in use on various maps)
 - /obj/machinery/door/airlock/ship/station/research
 - /obj/machinery/door/airlock/ship/cargo
- We still have /obj/machinery/door/airlock/ship/maintenance/defaultaccess (in use on various maps)

**Comment by covertcorvid** [comment]
These door types are useless but not actually an "issue"
