### ISSUE TITLE
Jeppison superthread

### ISSUE THREAD

**Issue by Vasily2013** [BeeStation/NSV13#608]
superthread for Jeppison

**Comment by Vasily2013** [comment]
- [ ] Deck Tech spawns
- [ ] 86 the window inside the bridge entrance
- [ ] reorganize bridge
- [ ] add decals to halls.
- [ ] Clutter the hallways some
- [ ] Look into a box-like theather?
- [ ] remove service techfab from the bar
- [ ] alter kitchen
- [ ] remove techfab from freezer
- [ ] add light to sec equipment locker
- [ ] check flight bay doors
- [ ] one-way doors to XO line
- [ ] XO line shutters
- [ ] Public request console for cargo
- [ ] move cargo card table north
- [ ] atmos door tiles
- [ ] put a ceiling over the MAA's office
- [ ] add color to RND public service
- [ ] extend torp console in toxins out one wall
- [ ] add FTL console to the ship
- [ ] remove one slime management console
- [ ] up security level on airlocks to tp room
- [ ] add symetry to the grav gen, add lights, decals, fluff

**Comment by Bokkiewokkie** [comment]
About engineering:
- Chief engineer office has no keycard authentication device
- There's a lot of scrubbers and pumps in _engineering_. (maybe change that completely useless 
  atmos room into a pump and scrubber storage)
- Not even Vago has o2 and fire lockers in engineering, engineers are well enough equipped to deal 
  with fire
- Why does the regular storage room have things that are literally in the lockers in the other hallway 
  in it? I think it'd be better to remove some of the random item racks, put the actual engineering 
  equipment lockers in the engineering storage and move the rad lockers to where those equipment 
  lockers are now.
- The stormdrive gas output pipe is below the floor and continues to go under a wall for a while, 
  maybe put it somewhere more visible.
- The plasma constrictor room only has an air scrubber and not a vent.
- Atmosians usually don't like it when you not only give them a very small room, but then also 
  decide to put layered waste and air pipes and vents and scrubbers in the room which even further 
  decreases the amount of useful space.
- Why is the teleporter in the AI lounge room? the teleporter is a CE access place and the AI upload/core is a RD access place. 

About engineering secure storage:
- I get that it's fun to put some emitters and a mirror in there but 3 emitters seems like a bit much, 
  maybe only give em 1.
- When would engineering need empty crates? just put the solar panel crate (or maybe 2) in there.
- Usually Nanotrasen doesn't just give us a free hypernobelium canister.

Other things:
- With how the ceiling above medical is now you can still land on the wall, which still allows you to break in.
- Why do the external airlocks have a pump and a canister attached via connectors in them instead of an oxygen tank and EVA suit? It's understandable you don't want to give away free EVA gear but why do you have to run around the station with your pump to collect air to refill your air tank?
- Half of the maints just contain emergency lockers, now it's understandable that there's a few of them near places in maint that are close to the main hallway or departments, but with the small maint this ship has already maybe put in some more ~lootboxes~ random stuff in maint and another unique maint room because right now the only cool place to be is the maint medbay.

**Comment by Vasily2013** [comment]
Alright, rebuttle to the unchecked areas.
-Yes, I know, atmosians don't like having to deal with air and scrubber pipes in small areas, but it's either a distro and scrubber system or not. It's as confined as I could make it. 
-This was off of guidance from the Hammerhead, who has a TP in science. I'll look into moving it, but at the moment I don't see a major issue in allowing it to remain in place.
-the pump and canister is to vent the air out of the airlock, not to refill your air tank. Anyone with external airlock access should already have access to means to refill their o2 tank.
-I'll look into more maint rooms in the future, but due to the odd shape and dimensions until we've got more random maint rooms i'm sorta wasted with building maint.

**Comment by ikalpo** [comment]
Robotics Lab needs a RnD console for the exosuit fabs to connect to

**Comment by Firefox13** [comment]
Science protholates are very fucking outadated ones, they don't have a type and can be interacted only with console.
And there are two of them, why.

**Comment by Firefox13** [comment]
Medbay lacks suit sensors consoles.

**Comment by Spyder904** [comment]
God I love this ship already.
Permabrig isn't accessible to Officers, because of Warden's office
Donut boxes are fake, no donuts in them. Sad.
**Legcuffs**
Prisoner transfer center is literally just a mass driver. With a GLASS windoor. The button is Toxins access, not sec access. Based.
One pair of shoes for EVERYONE in perma- you monster.
No Brig Phys locker
No area to put contra in, unless you count the SINGULAR locker in warden's office.
No camera or sec consoles in lobby area, only Warden or HOS can access either
My will to live has fled, can you please add it back

**Comment by Return-To-Sender-Fender-Bender** [comment]
Arrivals shuttle south airlocks drop you into maintenance with no way back up. if you're unlucky you will fall into a completely walled off area with a friendly, immoveable, torpedo named Jorge.

**Comment by Kmc2000** [comment]
> Arrivals shuttle south airlocks drop you into maintenance with no way back up. if you're unlucky you will fall into a completely walled off area with a friendly, immoveable, torpedo named Jorge.

Catwalks would solve this

**Comment by Vasily2013** [comment]
Continued fixes

- [x] Suit sensor console added to medbay, handheld monitors to doctors closets
- [x] Added real donuts to the donut boxes. (Restocking crews are now IPCs, and thus do not munch on the donuts.)
- [x] Officers not having access to perma isn't really that big of an issue in my eyes. Ensure your COC within the department is filled and that the Warden is doing his job. It should take someone of at least Warden status to perma someone anyways.
- [x] Legcuffs are fun, and will not be removed.
- [x] Button in the transfer ejector changed to armory access. (That's right, nobody with bog standard bridge access is able to vent someone into space)
- [x] Shoes added to Warden's perma storage locker, so now the real atrocity is only two beds.
- [x] Brig "doctor" now has a locker.
- [x] Added two evidence lockers to sec (Near the armory entrance)
- [x] Camera console added to the common brig area.
- [x] Error 404: Will2Live.exe not found. 
- [x] Catwalks added to arrivals area because APPARENTLY people can't see that they're not supposed to walk out of a door that goes nowhere.
- [x] MAGCAT added to launch bay, as well as some tiny fans.
- [x] Buttons for hangar doors fixed
- [x] Added a techfab to the desk position in science.
- [x] Added RnD console to robotics
- [x] Added more viewscreens

**Comment by Firefox13** [comment]
>  Officers not having access to perma isn't really that big of an issue in my eyes. Ensure your COC within the department is filled and that the Warden is doing his job. It should take someone of at least Warden status to perma someone anyways.

I thought Jeppison is low pop map.

**Comment by Firefox13** [comment]
Kitchen lacks universal enzyme.

**Comment by Vasily2013** [comment]
> I thought Jeppison is low pop map.
Keep your chain of command filled.

**Comment by ondrej008** [comment]
The Hangar bay has no anti-ship torps, only anti-fighter missiles. And a lot of those missiles...

**Comment by Karmic-Skink** [comment]
ISSUE: There is a pretender in maint. UNACCEPTABLE.

**Comment by Vasily2013** [comment]
> The Hangar bay has no anti-ship torps, only anti-fighter missiles. And a lot of those missiles...

The ship also has no anti-ship fighters in the hangar bay. There are big missiles in the forward magazines.

**Comment by Vasily2013** [comment]
> ISSUE: There is a pretender in maint. UNACCEPTABLE.

there is no longer an imposter.

**Comment by Firefox13** [comment]
Can QM access bridge hallway? They have access to vault as well as their remote can open it, soQM should be able to get in bridge hallway.

**Comment by DrSirKnight** [comment]
Left side exosuit fabricator in robotics can't sync with RnD database

**Comment by DrSirKnight** [comment]
Theater has 2 firelocks under 1 door tile
![](https://i.gyazo.com/bc0adb338f8fbbd4da070acc8bc7f38e.png)

**Comment by Vasily2013** [comment]
Things to add to perma
- [ ]Seed vendor
- [ ]sink
- [ ]bucket
- [ ]botany bag

**Comment by DrSirKnight** [comment]
![thdghdsdf](https://user-images.githubusercontent.com/54851612/83278025-99e43100-a1db-11ea-8ea5-84dcbf5d34e2.png)
These buttons seem to do nothing

**Comment by Firefox13** [comment]
CMO office lacks Runtime

**Comment by Cenrus** [comment]
Disturbing lack of firelocks on most doors

**Comment by Cenrus** [comment]
No robotics wardrobe vendor

**Comment by Cenrus** [comment]
No bartender wardrobe vendor

**Comment by Cenrus** [comment]
No geneticist wardrobe vendor

**Comment by Cenrus** [comment]
No Cargo wardrobe vendor

**Comment by Cenrus** [comment]
No chef wardrobe vendor

**Comment by Cenrus** [comment]
riot armoury shutters dir vars need to be set to 4

**Comment by DrSirKnight** [comment]
AI core air alarms are facing the opposite direction

**Comment by MayhemSailor** [comment]
Multi-Z adapters under an airlock door:
<img width="332" alt="JupMultiZ" src="https://user-images.githubusercontent.com/20588296/83283079-75fafe00-a18f-11ea-8817-b60b1e6902de.png">

Space pipe will not be monstermos compliant:
<img width="337" alt="JepSpacePipe" src="https://user-images.githubusercontent.com/20588296/83283111-84491a00-a18f-11ea-916f-c4216baf1a8e.png">

Arrivals multi-z issues:
<img width="1050" alt="JepArrivals" src="https://user-images.githubusercontent.com/20588296/83283128-8dd28200-a18f-11ea-8061-a70872ad8a24.png">

**Comment by DrSirKnight** [comment]
AI core isn't wired correctly, upload will lose power even if stormdrive is online

**Comment by DrSirKnight** [comment]
No cameras in chapel

**Comment by Vasily2013** [comment]
- [ ] Add runtime
- [ ] Add at least partially powered roundstart SMES
- [ ] add ID restriction to the service room. (Not sure how this wasn't foudn earlier.)
- [ ] add cameras to chapel ("It's a holy place, and that's one of the places with holes in the security net."
- [ ] Add AI upload access to power grid
- [ ] Power from space to AI core does not connect (woops)
- pipes will be corrected during the monstormos compatibility phase. I'll make those changes directly to Jalleo's branch.

**Comment by Vasily2013** [comment]
> No cameras in clown/mimes room

That'd be akin to cameras in the bathroom. There aren't many isolated places on this ship that don't have cameras, so that will remain one.

> AI core air alarms are facing the opposite direction

They're backwards because they're monitoring the air pressure of the buffer space around the AI core. It's just another defensive measure.

Mayhem
-The multiz adaptors under the airlock are sorta forced in placement.  I can't really put them anywhere else due to the fact that they have to be north-south.
-Spacepipes will be corrected with the rebase, and changes will be submitted directly to Jaleo's branch as mentioned earlier.
-If you're referencing the fire alarm that's because multi-z is a bit jank. Correcting that is outside of the scope of the PR. I've idiot proofed it as much as i'm going to but somewhere I've got to draw the line. I've added in some catwalks, removed the room where you could get stuck in, and blocked off medbay and the MAA's office. I've made the arrivals doors require external airlock access to go back the wrong way out of. I've done as much as I can but I can only stupid-proof so much!

**Comment by Corsaka** [comment]
![image](https://user-images.githubusercontent.com/23699128/83331472-952c8500-a28e-11ea-9ccd-e99aa8c492eb.png)
This specific maintenance door below bridge is not affected by emergency access.

**Comment by Corsaka** [comment]
`ADMIN LOG: An attempt to spawn space ninja returned , this is a bug.`
I would assume this means there's no mapped in spawns.

**Comment by Corsaka** [comment]
Next to teleporter room: WHY?
![image](https://user-images.githubusercontent.com/23699128/83332243-f144d880-a291-11ea-914d-47ba87f172a0.png)

**Comment by Vasily2013** [comment]
Changelog
-edited areas so those doors are all in maint now
-added carp spawns in, that should provide for ninjas as well.

Notes
-I believe that those default sprite airlocks were built after round start, as I do not see them anywhere in the area.

**Comment by Cenrus** [comment]
no disposal bin in the brig

**Comment by Firefox13** [comment]
Lighswitches in HALLWAYS.
They should exist in rooms/offices. NOT IN HALLWAYS.

**Comment by Firefox13** [comment]
![изображение](https://user-images.githubusercontent.com/57810301/84527717-12bcb000-ace7-11ea-94e2-0db52b89285a.png)
Place tiles instead of plating,

**Comment by Firefox13** [comment]
Brig lacks blast doors.
