### ISSUE TITLE
Medical Megathread

### ISSUE THREAD

**Issue by Corsaka** [BeeStation/NSV13#91]
Referencing https://github.com/DDMers/NSV13/issues/84 and my own issue;

Virology currently has no office, there are two geneticist slots when there's only one station, and there are generally a few too many medical doctors for such a cramped space.

...this feels like it should be longer for the term "megathread" tbh but like

**Comment by gryffinp** [comment]
so

SO

I kind of want to fuck with medicine. Specifically I want to make everyone unhappy, first by angering the fast medicine camp by removing the exceedingly effective syptic/sulfa meta, and then by annoying the hardcore medicine camp by not going too far enough and not adding any more complex systems like bone breaks or infected wounds. In general I have the following ideas, sorted in rough order of radicalness:

- Port TG Prs #[45104](https://github.com/tgstation/tgstation/pull/45104)(Organ/defib rework), as well as [#45953](https://github.com/tgstation/tgstation/pull/45953 ), [#46139](https://github.com/tgstation/tgstation/pull/46139), [#46512]((https://github.com/tgstation/tgstation/pull/46512), and various other Tend Wounds fixes and buffs. This, I think, should be done no matter what; Making tend wounds robust and giving doctors a challenging and rewarding alternative to simply dumping a body in cloning and fixing the new one goes a _huuuge_ way towards making surgery make sense as an option.

- Remove styptic powder and sulfadazine (and maybe charcoal?) and a handful of other chems that they made redundant anyway  and replace them with what I'm extremely tentatively calling "Restchems". The meaningful differences are: "restchems" metabolize much more quickly, requiring larger dosages for full healing,(Have you ever considered the dosage to healing ratios on goonchems? It's kinda nuts.) and they're relatively weak healing when you're up and walking around, but get significantly multiplied if you are resting in bed/asleep/in a cryo pod. The idea being that if you're lightly wounded and just need a quick boost, you can apply some and go about your business. But if a patient is badly hurt and needs significant healing, a doctor should put them in a bed or in cryo and apply the medicine, for robust amounts of recovery. I've coded up a simple proc to generate a healing multiplier based on status, right now it outputs 25% for standing patients, 75% for sleeping or bed-resting patients, and 100% for patients sleeping in a proper bed or cryopod. But those numbers could be tweaked simply enough.

- Speaking of cryo, remove cryoxadone. Cryo tubes are actually fairly interesting in their functionality, in the way that they massively multiply the amount of reagents inserted into them. But the reality of their use is that cryoxadone simply solves every problem and never ever runs out, so they're just the machine that fixes people instantly. I'd like to see a _little_ more interaction in the cryo process, by making doctors actually have to choose a medicine to apply in massive doses. "Restchems" should synergize very well with cryostasis, as the tubes would alleviate the downside of requiring large doses while simultaneously giving the best healing multiplier bonus. In my optimistic dreams, I envision a situation where a wounded person comes into medbay and has the options of taking some medicine and leaving to try to walk it off, going in and resting in a patient bed, or hopping into a cryo tube and getting massively healed at the cost of spending a moment in cryo. (reminder that upgrading a cryo tube with advanced parts not only increases the reagent multiplier but also reduces the wake up time for a released patient.

OBVIOUS PITFALL TO THE ABOVE: Cryo tubes right now auto-open when a patient reaches 100 health. This works because cryoxadone fixes everything, so most patients inserted into a working cryo tube will reach 100 health. If I remove cryox and get doctors to actually choose to apply medicines, there WILL be people who get put into a cryotube that does not have a medicine to fix one of their damage types. I may tweak the auto-eject code to also boot patients whose health hasn't moved for a few seconds, or at least sound a warning on medical radio.

OH ALSO: Imma keep CLONExadone in some form, because I think stuffing a fresh clone into a cryo tube is a reasonable and flavorful thing to do, and I also am into the ghetto solution of using a wrenched freezing cold shower.

- This is my most radical idea, it just occurred to me 40 minutes ago and might be terrible and need to get tossed in the trash: I'm considering the implications of removing Chemist as a dedicated job, and just giving Doctors access to the chemistry machines. The worst thing about being a Medical Doctor is the feeling of being dependent on Chemists to provide you the tools you *need* to do your job. Even if the higher RP standard of NSV13 relative to TG and other station servers might _hopefully_ reduce the number of chemists who just want to make bombs and speed and don't give a single shit about medicine, but the problem still exists even when there are useful chemists. I'd like to hope that the problem would be further alleviated by a shelf or locker full of bottles of "restchems" next to the cryo tubes, but the thought did occur to me earlier to just remove the distinction between chemists and doctors entirely, and treat chemistry in a manner more akin to a station's Toxins or Xenobiology department, that is, a sub-area of a larger department that anyone can access if they have a need but is usually claimed by one or two members. Obviously, removing an entire role is a big change and far from married to the idea, I've caught it's eye in a crowded bar at best. But it is a thought.

Anyway you may now begin yelling at me.

**Comment by covertcorvid** [comment]
Map complaints:
- Chemistry can't reach their fridge
- Need trash cans or disposals somewhere
- If we don't remove cryoxadone as gryffin suggested, there should probably be at least a little bit already there at round-start so docs don't have to wait on the chemists to be able to set up

**Comment by Karmic-Skink** [comment]
We haven't messed with job slots at this point, we'll get around to it at some point.
